name: setup-rokit

inputs:
  version:
    description: "`rokit` git tag (usually in the form vx.x.x)"
    required: false
  path:
    description: "Path to the `rokit.toml` directory"
    default: "."
    required: false
  cache:
    description: "Whether to enable caching"
    default: "false"
    required: false
  token:
    description: "GitHub token via `github.token`"
    default: "${{ github.token }}"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download rokit
      run: |
        case ${{ runner.arch }} in
          "X86" | "X64") fileArch="x86_64" ;;
          "ARM" | "ARM64") fileArch="aarch64" ;;
        esac

        case ${{ runner.os }} in
          Linux) pattern="*linux-$fileArch.zip" ;;
          macOS) pattern="*macos-$fileArch.zip" ;;
          Windows) pattern="*windows-$fileArch.zip" ;;
        esac

        gh release download ${{ inputs.version }} --repo rojo-rbx/rokit --pattern $pattern
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash

    - name: Install rokit
      run: |
        unzip rokit*.zip
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          ./rokit.exe self-install
        else
          ./rokit self-install
        fi
      shell: bash

    - name: Delete artifacts
      run: |
        rm rokit*.zip
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          rm rokit.exe
        else
          rm rokit
        fi
      shell: bash

    - name: Set environment variable
      if: runner.os == 'Windows'
      run: echo "$HOME/.rokit/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Set environment variable
      if: runner.os != 'Windows'
      run: echo "$HOME/.rokit/bin" >> $GITHUB_PATH
      shell: bash

    - name: Authenticate with GitHub
      run: rokit authenticate --token "${{ inputs.token }}" github
      shell: bash

    - name: Cache binaries
      if: ${{ inputs.cache == true || inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.rokit/bin
          ~/.rokit/tools
        key: ${{ runner.os }}-rokit-${{hashFiles(format('{0}/{1}', inputs.path, 'rokit.toml'))}}

    - name: Install tools
      run: |
        cd ${{ inputs.path }}
        rokit install --no-trust-check
      shell: bash
